// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1sc20cHYiTD0YlHHKI9EinYeFKpt9Rs',
    appId: '1:1035413810971:web:6e8db593c6893420132dbe',
    messagingSenderId: '1035413810971',
    projectId: 'wmcmplz',
    authDomain: 'wmcmplz.firebaseapp.com',
    storageBucket: 'wmcmplz.appspot.com',
    measurementId: 'G-NR1VY7R2RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDze4UgFIxpsqqVQQ8HvhnO7YjLzJaDg0',
    appId: '1:1035413810971:android:ed5ce97b9fd518f0132dbe',
    messagingSenderId: '1035413810971',
    projectId: 'wmcmplz',
    storageBucket: 'wmcmplz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKr5bVsQ0lpS859qDethh6jrBtXjCOinA',
    appId: '1:1035413810971:ios:80584d3838e394ae132dbe',
    messagingSenderId: '1035413810971',
    projectId: 'wmcmplz',
    storageBucket: 'wmcmplz.appspot.com',
    iosBundleId: 'com.example.wmcmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKr5bVsQ0lpS859qDethh6jrBtXjCOinA',
    appId: '1:1035413810971:ios:80584d3838e394ae132dbe',
    messagingSenderId: '1035413810971',
    projectId: 'wmcmplz',
    storageBucket: 'wmcmplz.appspot.com',
    iosBundleId: 'com.example.wmcmapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd1sc20cHYiTD0YlHHKI9EinYeFKpt9Rs',
    appId: '1:1035413810971:web:64f9433286835ecf132dbe',
    messagingSenderId: '1035413810971',
    projectId: 'wmcmplz',
    authDomain: 'wmcmplz.firebaseapp.com',
    storageBucket: 'wmcmplz.appspot.com',
    measurementId: 'G-M5SWQFC1XZ',
  );

}